language: java
# use Java 8
jdk:
  - openjdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

after_success:
  - mvn clean test jacoco:report coveralls:report

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

branches:
  only:
    - master